export const editorOptions: any = {
  acceptSuggestionOnCommitCharacter: true,
  acceptSuggestionOnEnter: "on",
  accessibilitySupport: "auto",
  autoIndent: true,
  automaticLayout: true,
  codeLens: true,
  colorDecorators: true,
  contextmenu: true,
  cursorSmoothCaretAnimation: false,
  disableLayerHinting: false,
  disableMonospaceOptimizations: false,
  dragAndDrop: false,
  fixedOverflowWidgets: false,
  folding: true,
  foldingStrategy: "auto",
  fontLigatures: false,
  formatOnPaste: false,
  formatOnType: false,
  // hideCursorInOverviewRuler: false,
  highlightActiveIndentGuide: true,
  links: true,
  mouseWheelZoom: false,
  multiCursorMergeOverlapping: true,
  multiCursorModifier: "alt",
  quickSuggestions: true,
  quickSuggestionsDelay: 100,
  readOnly: false,
  renderControlCharacters: false,
  renderFinalNewline: true,
  renderIndentGuides: true,
  // renderLineHighlight: "all",
  renderWhitespace: "none",
  revealHorizontalRightPadding: 30,
  roundedSelection: true,
  // rulers: [],
  scrollBeyondLastColumn: 5,
  scrollBeyondLastLine: true,
  selectOnLineNumbers: true,
  selectionClipboard: true,
  selectionHighlight: true,
  smoothScrolling: false,
  suggestOnTriggerCharacters: true,
  wordBasedSuggestions: true,
  wordSeparators: "~!@#$%^&*()-=+[{]}|;:'\",.<>/?",
  wordWrap: "off",
  wordWrapBreakAfterCharacters: "\t})]?|&,;",
  wordWrapBreakBeforeCharacters: "{([+",
  wordWrapBreakObtrusiveCharacters: ".",
  wordWrapColumn: 80,
  wordWrapMinified: true,
  wrappingIndent: "indent",
  showFoldingControls: "always",
  rulers: [
    {
      color: "#86939F",
      // column: 0.1,
    },
  ],
  renderLineHighlight: "none",
  lineHeight: 30,
  cursorStyle: "line",
  mouseStyle: "default",
  // wordWrap: "on",
  overviewRulerLanes: 2,
  overviewRulerBorder: true,
  hideCursorInOverviewRuler: true,
  lineNumbers: "on",
  lineNumbersMinChars: 0,
  // smoothScrolling: true,
  // cursorSmoothCaretAnimation: true,
  // suggest: {
  //   showColors: true,
  //   showIcons: true,
  //   showInlineDetails: true,
  //   showStatusBar: true,
  //   showWords: true,
  //   shareSuggestSelections: true,
  // },
  // "semanticHighlighting.enabled": "configuredByTheme",
  // autoIndent: "advanced",
  // codeLens: true,
  // padding: { bottom: 5, top: 5 },
  // disableLayerHinting: true,
  minimap: {
    enabled: true,
  },
  cursorBlinking: "blink",
  fontSize: 14,
};
export const SQLKeywords: any = [
  {
    label: "Select",
    detail: "Keyword",
    insertText: "SELECT",
    documentation: "sql selector.",
  },
  {
    label: "limit",
    insertText: "LIMIT",
    detail: "Keyword",
    documentation: "sql limit.",
  },
  {
    label: "where",
    insertText: "WHERE",
    detail: "Keyword",
    documentation: "sql keyword.",
  },
  {
    label: "orderby",
    insertText: "ORDER BY",
    detail: "Keyword",
    documentation: "sql keyword.",
  },
  {
    label: "min",
    insertText: "MIN",
    detail: "Keyword",
    documentation: "sql keyword.",
  },
  {
    label: "max",
    insertText: "MAX",
    detail: "Keyword",
    documentation: "sql keyword.",
  },
  {
    label: "from",
    insertText: "FROM",
    detail: "Keyword",
    documentation: "sql keyword.",
  },
  {
    label: "create",
    insertText: "CREATE",
    detail: "Keyword",
    documentation: "sql selector.",
  },
];
